#!/bin/bash

set -e

echo "Decidim OCL frontend build: installing js libs with yarn ..."

cd frontend

yarn install --frozen-lockfile

# fixes node-sass missing binary error
npm rebuild node-sass --force

#echo "Decidim OCL frontend build: building ..."
npm run build:prod:ci

cd ..

mkdir -p public
mv frontend/dist/* public

