name: 'Build Upgrade on push to upgrade branch'

on:
  push:
    branches:
      - 'upgrade'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-image:
    uses: ./.github/workflows/reusable_lint_test_build_update.yaml
    with:
      image_repo: "https://harbor.puzzle.ch"
      image_url: "harbor.puzzle.ch/decidim/stlu-dev-rails"
      configmanagement: "gitlab.puzzle.ch/pitc_ruby/deployments/decidim/"
      configmanagement_branch: "main"
      kustomization_path: "./deployments/pitc-stlu-decidim-dev/kustomization.yaml"
    secrets: inherit
