name: 'Build INT on push to master'

on:
  push:
    branches:
      - 'master'
      - 'feature/cloudscale'
    paths-ignore:
      - 'doc/**'
      - '**.md'
jobs:
  build-image:
    uses: ./.github/workflows/reusable_lint_test_build_update.yaml
    with:
      image_repo: "harbor.puzzle.ch/decidim/stlu/int/rails"
      configmanagement: "gitlab.puzzle.ch/pitc_ruby/decidim-configmanagement"
      kustomization_path: "./deployments/pitc-stlu-decidim-int/kustomization.yaml"


