name: 'Lint, test and build image. Push image tag to configmanagement'

on:
  workflow_call:
    inputs:
      image_repo:
        description: "Image repo to push image to"
        type: string
        required: true
      configmanagement:
        description: "Configmanagement to write image tag to"
        type: string
        required: true
      kustomization_path:
        description: "Path to kustomization file"
        type: string
        required: true

jobs: 
  lint:
    uses: ./.github/workflows/reusable_lint.yaml
  test:
    uses: ./.github/workflows/reusable_tests.yaml
  build:
    needs: [lint, test]
    uses: ./.github/workflows/reusable_build.yaml
    secrets: inherit
    with:
      repository_url: ${{ inputs.image_repo }}
  update_tag:
    needs: [build]
    uses: ./.github/workflows/reusable_update_image.yaml
    secrets: inherit
    with:
      repository: ${{ inputs.configmanagement }}
      file: ${{ inputs.kustomization_path }}
      json: ${{ jobs.build.outputs.json }}
